=== LuzRdgz/Schema_XML/song.dtd
<!ELEMENT Canciones (Cancion)*>
<!ELEMENT Cancion (titulo,compositores,productores,sello,artista)*>
        <!ATTLIST Cancion
                duracion CDATA #REQUIRED
                anio CDATA #REQUIRED>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT compositores (compositor)*>
    <!ELEMENT compositor (nombres|apellidos)*>
    <!ELEMENT nombres (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT productores (productor)*>
    <!ELEMENT productor (nombres|apellidos)*>
    <!ELEMENT sello (#PCDATA)>
    <!ELEMENT artista (#PCDATA)>

=== LuzRdgz/Schema_XML/song.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Canciones SYSTEM "song.dtd">
<Canciones>
    <Cancion duracion="4:47" anio="2008">
        <titulo>Give it 2 me</titulo>
        <compositores>
            <compositor>
                <nombres>Pharrell</nombres>
                <apellidos>Williams</apellidos>
            </compositor>
        </compositores>
        <productores>
            <productor>
                <nombres>Pharrell</nombres>
                <apellidos>Williams</apellidos>
            </productor>
        </productores>
        <sello>Warner Bros. Records</sello>
        <artista>Madonna</artista>
    </Cancion>
    <Cancion duracion="4:56" anio="2015">
        <titulo>Hello</titulo>
        <compositores>
            <compositor>
                <nombres>Adele</nombres>
                <apellidos>Adkins</apellidos>
            </compositor>
            <compositor>
                <nombres>Greg</nombres>
                <apellidos>Kurstin</apellidos>
            </compositor>
        </compositores>
        <productores>
            <productor>
                <nombres>Greg</nombres>
                <apellidos>Kurstin</apellidos>
            </productor>
        </productores>
        <sello>XL Recordings</sello>
        <artista>Adele Adkins</artista>
    </Cancion>
    <Cancion duracion="3:49" anio="2016">
        <titulo>Pulse</titulo>
        <compositores>
            <compositor>
                <nombres>Hyun Woo</nombres>
                <apellidos>Ha</apellidos>
            </compositor>
        </compositores>
        <productores>
            <productor>
                <nombres>Hyun-Woo</nombres>
                <apellidos>Ha</apellidos>
            </productor>
            <productor>
                <nombres>Kyu-ho</nombres>
                <apellidos>Jeon</apellidos>
            </productor>
            <productor>
                <nombres>Jung-gil</nombres>
                <apellidos>Lee</apellidos>
            </productor>
            <productor>
                <nombres>Ki-bum</nombres>
                <apellidos>Kim</apellidos>
            </productor>
        </productores>
        <sello>Interpack Corporation</sello>
        <artista>Guckkasten</artista>
    </Cancion>
</Canciones>
